### ISSUE TITLE
[TextArea] or multiple line string support

### ISSUE THREAD

**Issue by dburongarcia** [upscalebaby/generic-serializable-dictionary#9] opened 2021-01-16 11:47 UTC
Hi, I tried to use [TextArea] with GenericDictionary, but it doesn't support it. Is there any other way to show a multiple line string in the inspector? Thanks

**Comment by upscalebaby** [comment] 2021-01-16 14:52
Cool! I haven't tried this myself but I'll have some time free tomorrow to check it out, I'll get back to you once I have more info!

**Comment by upscalebaby** [comment] 2021-01-19 21:26
@dburongarcia sorry for the delay in looking into this!

Since attributes typically are used for modifying the behavior of a field (as a whole) I'm not sure implementing hard coded support for [TextArea] feels like a good fit in this case.

How do you feel about creating a wrapper for your class instead?

This is an example of how it looks when creating a wrapper class for the value-type for instance:

![image](https://user-images.githubusercontent.com/12954999/105094447-96702380-5aa4-11eb-8ab6-cd72107bf27a.png)

This already works and can be used for both Keys and Values - here's the source code I used in the above example:

```
[System.Serializable]
public class TextAreaWrapper
{
    [TextArea]
    public string text;
}
```

**Comment by dburongarcia** [comment] 2021-01-19 23:26
That sounds reasonable. I'd rather use a generic way and I think TextArea is a useful one, but your solution is an easy way to implement it and maybe not everyone needs TextArea. Thanks for your solution 👍

**Comment by upscalebaby** [comment] 2021-02-06 20:37
I've considered this some more and find it hard to strike a good balance. The problem is that I don't want to make assumptions in order to keep the tool as useable and simple as possible for all use cases.

A text input attribute would necessitate some arbitrary decisions to be made on behalf of the users. Should both key/value be targeted by the attribute, or should perhaps all strings present in the data structure be targeted?

I will close this issue with the proposed solution as the preferred way of solving this currently. But I really appreciate your feedback and don't hesitate to open more issues or discussions here in the future.

Thanks again for your support! 👍

**Closed by upscalebaby** 2021-02-06 20:37 UTC
