### ISSUE TITLE
Incorrect ICollection.CopyTo Behavior

### ISSUE THREAD

**Issue by is90** [upscalebaby/generic-serializable-dictionary#2] opened 2020-03-01 04:09 UTC
The CopyTo implementation always starts to copy members at index = 0, rather than starting at the provided arrayIndex parameter.

**Comment by upscalebaby** [comment] 2020-03-01 09:43
Thanks for opening an issue! I couldn't reproduce the error, calling CopyTo with an array and arrayIndex does return the array with correct results from my testing. Could you provide an example of it failing?

**Comment by is90** [comment] 2020-03-01 19:05
ICollection.CopyTo should copy all of the elements into the destination array, starting at the provided array index.

For example:

static void Main(string[] args)
        {
            IDictionary<int, bool> myDictionary = new Dictionary<int, bool>
            {
                {100, true},
                {200, true},
                {300, true}
            };

            var destinationArray = new KeyValuePair<int, bool>[5]
            {
                new KeyValuePair<int, bool>(0, false),
                new KeyValuePair<int, bool>(1, false),
                new KeyValuePair<int, bool>(2, false),
                new KeyValuePair<int, bool>(3, false),
                new KeyValuePair<int, bool>(4, false)
            };

            myDictionary.CopyTo(destinationArray, 2);

            foreach(var kvp in destinationArray)
            {
                Console.WriteLine(string.Format("Key = {0}, Value = {1}", kvp.Key, kvp.Value));
            }


            Console.ReadKey();
        }

Will copy all 3 elements into destinationArray, starting at index 2, and will print out
Key = 0, Value = False
Key = 1, Value = False
Key = 100, Value = True
Key = 200, Value = True
Key = 300, Value = True

**Comment by upscalebaby** [comment] 2020-03-02 09:35
> ICollection.CopyTo should copy all of the elements into the destination array, starting at the provided array index.

Ah didn't read the doc carefully enough and thus didn't fully understand the expected behaviour. Thanks taking the time to clarify this issue.

I have a bunch of improvements that I'm looking to push within the coming days, I will make sure to include a fix for this behaviour with that push! Thanks again!

**Closed** 2020-03-11 22:06 UTC
