### ISSUE TITLE
please add to package manager and asset store

### ISSUE THREAD

**Issue by linojon** [upscalebaby/generic-serializable-dictionary#17] opened 2021-05-23 12:18 UTC

**Comment by upscalebaby** [comment] 2021-05-23 12:49
Thanks for your support! I agree it's the most urgent step that I'm working toward. But since this is a duplicate of issue #16 I'm closing it, feel free to open further issues or discussion threads on this repo. Thanks again!

**Closed** 2021-05-23 12:49 UTC
